{"ast":null,"code":"import { Observable } from '../Observable';\nimport { isFunction } from '../util/isFunction';\nexport function throwError(errorOrErrorFactory, scheduler) {\n  var errorFactory = isFunction(errorOrErrorFactory) ? errorOrErrorFactory : function () {\n    return errorOrErrorFactory;\n  };\n  var init = function (subscriber) {\n    return subscriber.error(errorFactory());\n  };\n  return new Observable(scheduler ? function (subscriber) {\n    return scheduler.schedule(init, 0, subscriber);\n  } : init);\n}","map":{"version":3,"names":["Observable","isFunction","throwError","errorOrErrorFactory","scheduler","errorFactory","init","subscriber","error","schedule"],"sources":["/Users/mdabdurrazzak/RadInsu/node_modules/rxjs/src/internal/observable/throwError.ts"],"sourcesContent":["import { Observable } from '../Observable';\nimport { Subscriber } from '../Subscriber';\nimport { SchedulerLike } from '../types';\nimport { isFunction } from '../util/isFunction';\n\n/**\n * Creates an observable that will create an error instance and push it to the consumer as an error\n * immediately upon subscription.\n *\n * <span class=\"informal\">Just errors and does nothing else</span>\n *\n * ![](throw.png)\n *\n * This creation function is useful for creating an observable that will create an error and error every\n * time it is subscribed to. Generally, inside of most operators when you might want to return an errored\n * observable, this is unnecessary. In most cases, such as in the inner return of {@link concatMap},\n * {@link mergeMap}, {@link defer}, and many others, you can simply throw the error, and RxJS will pick\n * that up and notify the consumer of the error.\n *\n * ## Example\n *\n * Create a simple observable that will create a new error with a timestamp and log it\n * and the message every time you subscribe to it.\n *\n * ```ts\n * import { throwError } from 'rxjs';\n *\n * let errorCount = 0;\n *\n * const errorWithTimestamp$ = throwError(() => {\n *    const error: any = new Error(`This is error number ${++errorCount}`);\n *    error.timestamp = Date.now();\n *    return error;\n * });\n *\n * errorWithTimesptamp$.subscribe({\n *    error: err => console.log(err.timestamp, err.message)\n * });\n *\n * errorWithTimesptamp$.subscribe({\n *    error: err => console.log(err.timestamp, err.message)\n * });\n *\n * // Logs the timestamp and a new error message each subscription;\n * ```\n *\n * ## Unnecessary usage\n *\n * Using `throwError` inside of an operator or creation function\n * with a callback, is usually not necessary:\n *\n * ```ts\n * import { throwError, timer, of } from 'rxjs';\n * import { concatMap } from 'rxjs/operators';\n *\n * const delays$ = of(1000, 2000, Infinity, 3000);\n *\n * delays$.pipe(\n *    concatMap(ms => {\n *      if (ms < 10000) {\n *        return timer(ms);\n *      } else {\n *        // This is probably overkill.\n *        return throwError(() => new Error(`Invalid time ${ms}`));\n *      }\n *    })\n * )\n * .subscribe({\n *    next: console.log,\n *    error: console.error\n * });\n * ```\n *\n * You can just throw the error instead:\n *\n * ```ts\n * import { throwError, timer, of } from 'rxjs';\n * import { concatMap } from 'rxjs/operators';\n *\n * const delays$ = of(1000, 2000, Infinity, 3000);\n *\n * delays$.pipe(\n *    concatMap(ms => {\n *      if (ms < 10000) {\n *        return timer(ms);\n *      } else {\n *        // Cleaner and easier to read for most folks.\n *        throw new Error(`Invalid time ${ms}`);\n *      }\n *    })\n * )\n * .subscribe({\n *    next: console.log,\n *    error: console.error\n * });\n * ```\n *\n * @param errorFactory A factory function that will create the error instance that is pushed.\n */\nexport function throwError(errorFactory: () => any): Observable<never>;\n\n/**\n * Returns an observable that will error with the specified error immediately upon subscription.\n *\n * @param error The error instance to emit\n * @deprecated Support for passing an error value will be removed in v8. Instead, pass a factory function to `throwError(() => new Error('test'))`. This is\n * because it will create the error at the moment it should be created and capture a more appropriate stack trace. If\n * for some reason you need to create the error ahead of time, you can still do that: `const err = new Error('test'); throwError(() => err);`.\n */\nexport function throwError(error: any): Observable<never>;\n\n/**\n * Notifies the consumer of an error using a given scheduler by scheduling it at delay `0` upon subscription.\n *\n * @param errorOrErrorFactory An error instance or error factory\n * @param scheduler A scheduler to use to schedule the error notification\n * @deprecated The `scheduler` parameter will be removed in v8.\n * Use `throwError` in combination with {@link observeOn}: `throwError(() => new Error('test')).pipe(observeOn(scheduler));`.\n * Details: https://rxjs.dev/deprecations/scheduler-argument\n */\nexport function throwError(errorOrErrorFactory: any, scheduler: SchedulerLike): Observable<never>;\n\nexport function throwError(errorOrErrorFactory: any, scheduler?: SchedulerLike): Observable<never> {\n  const errorFactory = isFunction(errorOrErrorFactory) ? errorOrErrorFactory : () => errorOrErrorFactory;\n  const init = (subscriber: Subscriber<never>) => subscriber.error(errorFactory());\n  return new Observable(scheduler ? (subscriber) => scheduler.schedule(init as any, 0, subscriber) : init);\n}\n"],"mappings":"AAAA,SAASA,UAAU,QAAQ,eAAe;AAG1C,SAASC,UAAU,QAAQ,oBAAoB;AAuH/C,OAAM,SAAUC,UAAUA,CAACC,mBAAwB,EAAEC,SAAyB;EAC5E,IAAMC,YAAY,GAAGJ,UAAU,CAACE,mBAAmB,CAAC,GAAGA,mBAAmB,GAAG;IAAM,OAAAA,mBAAmB;EAAnB,CAAmB;EACtG,IAAMG,IAAI,GAAG,SAAAA,CAACC,UAA6B;IAAK,OAAAA,UAAU,CAACC,KAAK,CAACH,YAAY,EAAE,CAAC;EAAhC,CAAgC;EAChF,OAAO,IAAIL,UAAU,CAACI,SAAS,GAAG,UAACG,UAAU;IAAK,OAAAH,SAAS,CAACK,QAAQ,CAACH,IAAW,EAAE,CAAC,EAAEC,UAAU,CAAC;EAA9C,CAA8C,GAAGD,IAAI,CAAC;AAC1G","ignoreList":[]},"metadata":{},"sourceType":"module","externalDependencies":[]}